image: newcity/builder:node8

#from: https://nicolaw.uk/GitLabCiPushingWrites
variables:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa-gitlab-ci"
  GIT_STRATEGY: clone
  REMOTE_REPO: git@gitlab.com:uky-web/patternlab-artifact.git
  BUILD_REPO: /tmp/pl-artifact

before_script:
#- eval $(ssh-agent -s)
#- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
##- mkdir -p ~/.ssh
##- chmod 700 ~/.ssh


stages:
- build
- deploy

compile:assets:
  stage: build
  script:
  - cp docker/taskrunner/* .
  - npm install
  - gulp build-all
  artifacts:
    paths:
    - dist
    expire_in: 1 week
  #only:
  #- master

push:artifact:
  stage: deploy
  script:
  - cp docker/ci/Makefile.artifact ./Makefile
  - mkdir -pvm 0700 ${HOME}/.ssh
  - echo "$SSH_PRIVATE_KEY" > ${HOME}/.ssh/id_rsa-gitlab-ci
  - chmod 0600 ${HOME}/.ssh/id_rsa-gitlab-ci
  - make --version 
  - make clone
  - make replay
  - make push

pages:
  stage: build
  image:
  name: squidfunk/mkdocs-material
  entrypoint:
    - ""
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  # only:
  #   - master
  tags:
    - gitlab-org-docker
