version: '2'

services:
  # taskrunner to compile src
  taskrunner:
    environment:
      NPM_INSTALL: 1
    image: newcity/taskrunner:latest
    volumes:
      # map assets in and persistent storage containers out
      - ./assets:/app/assets:ro
      - css:/app/dist/css
      - js:/app/dist/js
      - images:/app/dist/images
      - fonts:/app/dist/fonts
      - sprites:/app/dist/sprites
      - intermediate:/app/intermediate
      # config overrides
      - ./docker/taskrunner/package.json:/app/package.json:ro
      - ./docker/taskrunner/gulpfile.js:/app/gulpfile.js:ro
      - ./.sass-lint.yml:/app/.sass-lint.yml:ro
    working_dir: /app

  # pattern lab compilation
  pl:
    image: newcity/pl:latest
    volumes:
      # bring in persistent storage assets and patterns
      - css:/pl/public/css:ro
      - js:/pl/public/js:ro
      - images:/pl/public/images:ro
      - sprites:/pl/source/sprites:ro
      - fonts:/pl/public/fonts:ro
      - ./src/_annotations:/pl/source/_annotations:ro
      - ./src/_data:/pl/source/_data:ro
      - ./src/_layouts:/pl/source/_layouts:ro
      - ./src/_macros:/pl/source/_macros:ro
      - ./src/_meta:/pl/source/_meta:ro
      - ./src/_patterns:/pl/source/_patterns:ro
      - ./src/_twig-components:/pl/source/_twig-components:ro
      # config overrides
      - ./docker/pl/gulpfile.js:/gulpfile.js:ro
      - ./docker/pl/config.yml:/pl/config/config.yml:ro
      - ./docker/pl/libraries.yml:/pl/config/libraries.yml:ro
    ports:
      # main webserver
      - "3000:3000"
      # browsersync setup
      - "3001:3001"

volumes:
  css:
  images:
  js:
  sprites:
  fonts:
  intermediate:
